# Generated by Django 3.1.6 on 2021-03-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20210315_1502'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='virdismart',
            table='Accounts',
        ),
    ]
